import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Certifications from "../components/Certifications";
import Contact from "../components/Contact";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Experience from "../components/Experiences";
import Volunteer from "../components/Volunteer";
import Skills from "../components/Skills";
import { useState, useEffect } from "react";
import { LineWave } from "react-loader-spinner";
import { fetcher } from "../lib/api";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Joades</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Main title={data.title} subTitle={data.subTitle} />
      <About
        aboutDesc={data.about.aboutDescription}
        aboutImg={data.about.aboutImage}
      />
      <Experience experience={data.experience} />
      <Skills skills={data.skills} />
      <Certifications certifications={data.certifications} />
      <Volunteer volunteerExperience={data.volunteerExperience} />
      <Contact />
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetcher(
    `${process.env.NEXT_PUBLIC_BASEURL}/api/home-page`
  );

  return {
    props: {
      data: response.data.attributes,
    },
  };
}
