import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Certifications from '../components/Certifications'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import Experience from '../components/Experiences'
import Volunteer from '../components/Volunteer'
import Skills from '../components/Skills'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Joades</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Main />
      <About />
      <Certifications />
      <Skills />
      <Experience />
      <Volunteer />
      
      <Contact />
    </div>
  )
}
